
services:
  dynamodb-local:
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
  
  unittest-pytest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unittest-pytest
    depends_on:
      dynamodb-local:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "aws dynamodb create-table --table-name cloud-resume --region ap-southeast-1 --attribute-definitions AttributeName=Id,AttributeType=S --key-schema AttributeName=Id,KeyType=HASH --billing-mode PAY_PER_REQUEST --table-class STANDARD --endpoint-url http://dynamodb-local:8000 && pytest"]
  
  cleanup:
    image: docker:latest
    container_name: cleanup
    entrypoint: ["/bin/sh", "-c", "docker stop dynamodb-local"]
    depends_on:
      unittest-pytest:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock